# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cookerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(451, 230)
        self.StirButton = QtWidgets.QPushButton(Dialog)
        self.StirButton.setGeometry(QtCore.QRect(30, 170, 93, 28))
        self.StirButton.setObjectName("StirButton")
        self.Pan1Label = QtWidgets.QLabel(Dialog)
        self.Pan1Label.setGeometry(QtCore.QRect(60, 10, 55, 16))
        self.Pan1Label.setObjectName("Pan1Label")
        self.Pan2Label = QtWidgets.QLabel(Dialog)
        self.Pan2Label.setGeometry(QtCore.QRect(200, 10, 55, 16))
        self.Pan2Label.setObjectName("Pan2Label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 170, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.Pan3Timer = QtWidgets.QTimeEdit(Dialog)
        self.Pan3Timer.setEnabled(False)
        self.Pan3Timer.setGeometry(QtCore.QRect(310, 40, 118, 22))
        self.Pan3Timer.setObjectName("Pan3Timer")
        self.Warning = QtWidgets.QLabel(Dialog)
        self.Warning.setGeometry(QtCore.QRect(180, 120, 55, 16))
        self.Warning.setObjectName("Warning")
        self.Pan2Timer = QtWidgets.QTimeEdit(Dialog)
        self.Pan2Timer.setEnabled(False)
        self.Pan2Timer.setGeometry(QtCore.QRect(160, 40, 118, 22))
        self.Pan2Timer.setObjectName("Pan2Timer")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(320, 80, 55, 16))
        self.label_10.setObjectName("label_10")
        self.Pan3Label = QtWidgets.QLabel(Dialog)
        self.Pan3Label.setGeometry(QtCore.QRect(330, 10, 55, 16))
        self.Pan3Label.setObjectName("Pan3Label")
        self.SturSelect = QtWidgets.QComboBox(Dialog)
        self.SturSelect.setGeometry(QtCore.QRect(40, 120, 73, 22))
        self.SturSelect.setObjectName("SturSelect")
        self.SturSelect.addItem("")
        self.SturSelect.addItem("")
        self.SturSelect.addItem("")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 80, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(180, 80, 55, 16))
        self.label_9.setObjectName("label_9")
        self.Pan1Timer = QtWidgets.QTimeEdit(Dialog)
        self.Pan1Timer.setEnabled(False)
        self.Pan1Timer.setGeometry(QtCore.QRect(10, 40, 118, 22))
        self.Pan1Timer.setObjectName("Pan1Timer")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.StirButton.setText(_translate("Dialog", "Stir"))
        self.Pan1Label.setText(_translate("Dialog", "Pan1"))
        self.Pan2Label.setText(_translate("Dialog", "Pan2"))
        self.pushButton.setText(_translate("Dialog", "Stop"))
        self.Warning.setText(_translate("Dialog", "Warning"))
        self.label_10.setText(_translate("Dialog", "TextLabel"))
        self.Pan3Label.setText(_translate("Dialog", "Pan3"))
        self.SturSelect.setItemText(0, _translate("Dialog", "Pan1"))
        self.SturSelect.setItemText(1, _translate("Dialog", "Pan2"))
        self.SturSelect.setItemText(2, _translate("Dialog", "Pan3"))
        self.label_8.setText(_translate("Dialog", "TextLabel"))
        self.label_9.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
